version: '3.5'
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      #- "82:80/tcp"
    # networks:
    #   - npm-net
    env_file:
      - pihole.env
    # environment:
    #  TZ:
    #  WEBPASSWORD:
    # Volumes store your data between container upgrades
    volumes:
      - '/home/$USER/docker/pi-hole/etc-pihole:/etc/pihole'
      - '/home/$USER/docker/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
      #- NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    #to build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /home/$USER/docker/my-homer-dashboard/assets/:/www/assets
    # networks:
    #   - npm-net
    environment:
      - init_assets=1
      - ipv6_disable=1
    # ports:
    #   - 8080:8080
    user: 1000:1000 # default
    restart: unless-stopped 

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      #- '81:81' # Comment out after creating a proxy host for the service
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # networks:
    #   - npm-net
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /home/$USER/docker/npm/data:/data
      - /home/$USER/docker/npm/letsencrypt:/etc/letsencrypt
      
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.13
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    ports:
      - 8088:8088
      - 8043:8043
      - 8843:8843
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Asia/Manila
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

  
volumes:
  omada-data:
  omada-logs:
  portainer-data:

# networks:
#   npm-net:
#     driver: bridge
