---
- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/devken0

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

- Cloud:
    - OneDrive:
        - abbr: OD
          href: https://onedrive.live
